// LIBS
import type { Metadata } from "next";
import localFont from "next/font/local";

// GLOBAL CSS
import "./globals.css";

// APP SHELL
import AppShell from "@/appshell/Index";

// FONT LOCAL 1
const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

// FONT LOCAL 2
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// METADATA
export const metadata: Metadata = {
    title: "YUDHA - DEV",
    description: "Generated by create next app",
};

// ROOT LAYOUT
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode;}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AppShell>
                    {children}
                </AppShell>
            </body>
        </html>
    );
}
